import {MigrationInterface, QueryRunner} from "typeorm";

export class migration1564322260652 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "category" ("name" character varying NOT NULL, "id" uuid NOT NULL, CONSTRAINT "UQ_23c05c292c439d77b0de816b500" UNIQUE ("name"), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "locations" ("coordinates" point NOT NULL, "name" character varying, "description" character varying, "verified" boolean NOT NULL, "id" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "authorId" uuid, CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("email" character varying NOT NULL, "verified" boolean, "password" character varying, "username" character varying, "image" character varying, "twitterId" character varying, "facebookId" character varying, "googleId" character varying, "id" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_eda3fd04bdb78a1c678fdb6ecc9" UNIQUE ("twitterId"), CONSTRAINT "UQ_f9740e1e654a5daddb82c60bd75" UNIQUE ("facebookId"), CONSTRAINT "UQ_f382af58ab36057334fb262efd5" UNIQUE ("googleId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "events" ("title" character varying NOT NULL, "startTime" TIMESTAMP WITH TIME ZONE, "endTime" TIMESTAMP WITH TIME ZONE, "description" character varying, "pricing" real, "pricingUnit" character varying, "ageRestriction" integer, "image" character varying, "backgroundImage" character varying, "color" character varying, "isPrivate" boolean, "isCapacityLimited" boolean, "isFreeInvite" boolean, "id" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "authorId" uuid, "locationId" uuid, CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users_interests_category" ("usersId" uuid NOT NULL, "categoryId" uuid NOT NULL, CONSTRAINT "PK_0d611de7586267dbf6be680acf6" PRIMARY KEY ("usersId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90a15f079b117647e5d267dc02" ON "users_interests_category" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_881f7d3889d88ab53bcaf5eb59" ON "users_interests_category" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "users_users_blocked_users" ("usersId_1" uuid NOT NULL, "usersId_2" uuid NOT NULL, CONSTRAINT "PK_2eb21128624d8d54400fd6e0a79" PRIMARY KEY ("usersId_1", "usersId_2"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a1bf6826f7f14b39329e0ad521" ON "users_users_blocked_users" ("usersId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a43449a5faadcc6dfe9cbba3c" ON "users_users_blocked_users" ("usersId_2") `);
        await queryRunner.query(`CREATE TABLE "users_users_friended_users" ("usersId_1" uuid NOT NULL, "usersId_2" uuid NOT NULL, CONSTRAINT "PK_c7384eab9f2bb6efbfbd7a8e340" PRIMARY KEY ("usersId_1", "usersId_2"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f666d2e77717f8c25f7b9b570b" ON "users_users_friended_users" ("usersId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_d26a4fce0d47c58f27b0f434e4" ON "users_users_friended_users" ("usersId_2") `);
        await queryRunner.query(`CREATE TABLE "users_events_subscribed_events" ("usersId" uuid NOT NULL, "eventsId" uuid NOT NULL, CONSTRAINT "PK_e906d76929cd7ebee14048f7ee8" PRIMARY KEY ("usersId", "eventsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5e1a5059bc9c16f55e092bad91" ON "users_events_subscribed_events" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_74c8a019e92aa8f46da55ce5c7" ON "users_events_subscribed_events" ("eventsId") `);
        await queryRunner.query(`CREATE TABLE "users_events_attended_events" ("usersId" uuid NOT NULL, "eventsId" uuid NOT NULL, CONSTRAINT "PK_18da362520377cbb3ca65cc7fe2" PRIMARY KEY ("usersId", "eventsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5c0fa4b1a599d09c968eadf55b" ON "users_events_attended_events" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f31992a49c73b5889663dbb26" ON "users_events_attended_events" ("eventsId") `);
        await queryRunner.query(`CREATE TABLE "users_events_attended_on_behalf_events" ("usersId" uuid NOT NULL, "eventsId" uuid NOT NULL, CONSTRAINT "PK_e30ce8cee70b84788974834a266" PRIMARY KEY ("usersId", "eventsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5f5b1cac95cd2a556c9a416f5b" ON "users_events_attended_on_behalf_events" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f428e8eb01f072bd78ce977cd9" ON "users_events_attended_on_behalf_events" ("eventsId") `);
        await queryRunner.query(`CREATE TABLE "users_events_invited_events" ("usersId" uuid NOT NULL, "eventsId" uuid NOT NULL, CONSTRAINT "PK_c16bbefc70e0d9d69c0d6c57610" PRIMARY KEY ("usersId", "eventsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c48949e1dcc02341ea8c61eec2" ON "users_events_invited_events" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5833bf6d88075d08b2e5b16270" ON "users_events_invited_events" ("eventsId") `);
        await queryRunner.query(`CREATE TABLE "users_events_moderated_events" ("usersId" uuid NOT NULL, "eventsId" uuid NOT NULL, CONSTRAINT "PK_faa184f68f027a8cc8b413df906" PRIMARY KEY ("usersId", "eventsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90375e090112b4910bbe9b3f98" ON "users_events_moderated_events" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_796d480a170fea3ea9c34dacdc" ON "users_events_moderated_events" ("eventsId") `);
        await queryRunner.query(`CREATE TABLE "events_categories_category" ("eventsId" uuid NOT NULL, "categoryId" uuid NOT NULL, CONSTRAINT "PK_c87cb91b874fada362f23d5eabb" PRIMARY KEY ("eventsId", "categoryId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db7766576cee46f8f492e5cf91" ON "events_categories_category" ("eventsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2a6d806d59cdae47f2cebd16b" ON "events_categories_category" ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "events_moderators_users" ("eventsId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_6740fac34aa7451c61161024d43" PRIMARY KEY ("eventsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6e4d7b93b5823354a0d67c91ad" ON "events_moderators_users" ("eventsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cb733c6969ffc6b8c24878755" ON "events_moderators_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "events_subscribers_users" ("eventsId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_4d2b2f053ff91b4acdf688e3224" PRIMARY KEY ("eventsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1236e491674525fdb404597e28" ON "events_subscribers_users" ("eventsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_765c0346ad3f288fa562eeb3da" ON "events_subscribers_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "events_attendees_users" ("eventsId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_75d2b75c2969af882491c8353b2" PRIMARY KEY ("eventsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc4d1dac2b0c139aa3c722401b" ON "events_attendees_users" ("eventsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_55e9eaa2a8199f6d56e8f851bc" ON "events_attendees_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "events_attendees_on_behalf_users" ("eventsId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_05fda4cbbc48798d8050ecbc023" PRIMARY KEY ("eventsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4b10e1dc612af5c704e6221f23" ON "events_attendees_on_behalf_users" ("eventsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2665f14d503b3feefefff8e877" ON "events_attendees_on_behalf_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "events_attendees_invited_users" ("eventsId" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_d1b6d58cb5dd1e9cc0a06b64631" PRIMARY KEY ("eventsId", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9caedc75d8c28cbe1da074d65b" ON "events_attendees_invited_users" ("eventsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dc98eb9fc9fecc8fba0e537169" ON "events_attendees_invited_users" ("usersId") `);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_ded332d78e4026526df1a7dc630" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_96ce126fb3f1b5368f8e3c02989" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events" ADD CONSTRAINT "FK_55ad94f5c1b4c97960d6d7dc115" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_interests_category" ADD CONSTRAINT "FK_90a15f079b117647e5d267dc024" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_interests_category" ADD CONSTRAINT "FK_881f7d3889d88ab53bcaf5eb598" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_users_blocked_users" ADD CONSTRAINT "FK_a1bf6826f7f14b39329e0ad5215" FOREIGN KEY ("usersId_1") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_users_blocked_users" ADD CONSTRAINT "FK_2a43449a5faadcc6dfe9cbba3c5" FOREIGN KEY ("usersId_2") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_users_friended_users" ADD CONSTRAINT "FK_f666d2e77717f8c25f7b9b570b5" FOREIGN KEY ("usersId_1") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_users_friended_users" ADD CONSTRAINT "FK_d26a4fce0d47c58f27b0f434e42" FOREIGN KEY ("usersId_2") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_events_subscribed_events" ADD CONSTRAINT "FK_5e1a5059bc9c16f55e092bad913" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_events_subscribed_events" ADD CONSTRAINT "FK_74c8a019e92aa8f46da55ce5c7d" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_events_attended_events" ADD CONSTRAINT "FK_5c0fa4b1a599d09c968eadf55bb" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_events_attended_events" ADD CONSTRAINT "FK_3f31992a49c73b5889663dbb266" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_events_attended_on_behalf_events" ADD CONSTRAINT "FK_5f5b1cac95cd2a556c9a416f5bb" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_events_attended_on_behalf_events" ADD CONSTRAINT "FK_f428e8eb01f072bd78ce977cd9b" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_events_invited_events" ADD CONSTRAINT "FK_c48949e1dcc02341ea8c61eec29" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_events_invited_events" ADD CONSTRAINT "FK_5833bf6d88075d08b2e5b162704" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_events_moderated_events" ADD CONSTRAINT "FK_90375e090112b4910bbe9b3f98e" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_events_moderated_events" ADD CONSTRAINT "FK_796d480a170fea3ea9c34dacdc3" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_categories_category" ADD CONSTRAINT "FK_db7766576cee46f8f492e5cf919" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_categories_category" ADD CONSTRAINT "FK_f2a6d806d59cdae47f2cebd16b7" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_moderators_users" ADD CONSTRAINT "FK_6e4d7b93b5823354a0d67c91ad0" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_moderators_users" ADD CONSTRAINT "FK_2cb733c6969ffc6b8c24878755e" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_subscribers_users" ADD CONSTRAINT "FK_1236e491674525fdb404597e282" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_subscribers_users" ADD CONSTRAINT "FK_765c0346ad3f288fa562eeb3da6" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_attendees_users" ADD CONSTRAINT "FK_cc4d1dac2b0c139aa3c722401b1" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_attendees_users" ADD CONSTRAINT "FK_55e9eaa2a8199f6d56e8f851bcd" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_attendees_on_behalf_users" ADD CONSTRAINT "FK_4b10e1dc612af5c704e6221f233" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_attendees_on_behalf_users" ADD CONSTRAINT "FK_2665f14d503b3feefefff8e8770" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_attendees_invited_users" ADD CONSTRAINT "FK_9caedc75d8c28cbe1da074d65bf" FOREIGN KEY ("eventsId") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "events_attendees_invited_users" ADD CONSTRAINT "FK_dc98eb9fc9fecc8fba0e537169f" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "events_attendees_invited_users" DROP CONSTRAINT "FK_dc98eb9fc9fecc8fba0e537169f"`);
        await queryRunner.query(`ALTER TABLE "events_attendees_invited_users" DROP CONSTRAINT "FK_9caedc75d8c28cbe1da074d65bf"`);
        await queryRunner.query(`ALTER TABLE "events_attendees_on_behalf_users" DROP CONSTRAINT "FK_2665f14d503b3feefefff8e8770"`);
        await queryRunner.query(`ALTER TABLE "events_attendees_on_behalf_users" DROP CONSTRAINT "FK_4b10e1dc612af5c704e6221f233"`);
        await queryRunner.query(`ALTER TABLE "events_attendees_users" DROP CONSTRAINT "FK_55e9eaa2a8199f6d56e8f851bcd"`);
        await queryRunner.query(`ALTER TABLE "events_attendees_users" DROP CONSTRAINT "FK_cc4d1dac2b0c139aa3c722401b1"`);
        await queryRunner.query(`ALTER TABLE "events_subscribers_users" DROP CONSTRAINT "FK_765c0346ad3f288fa562eeb3da6"`);
        await queryRunner.query(`ALTER TABLE "events_subscribers_users" DROP CONSTRAINT "FK_1236e491674525fdb404597e282"`);
        await queryRunner.query(`ALTER TABLE "events_moderators_users" DROP CONSTRAINT "FK_2cb733c6969ffc6b8c24878755e"`);
        await queryRunner.query(`ALTER TABLE "events_moderators_users" DROP CONSTRAINT "FK_6e4d7b93b5823354a0d67c91ad0"`);
        await queryRunner.query(`ALTER TABLE "events_categories_category" DROP CONSTRAINT "FK_f2a6d806d59cdae47f2cebd16b7"`);
        await queryRunner.query(`ALTER TABLE "events_categories_category" DROP CONSTRAINT "FK_db7766576cee46f8f492e5cf919"`);
        await queryRunner.query(`ALTER TABLE "users_events_moderated_events" DROP CONSTRAINT "FK_796d480a170fea3ea9c34dacdc3"`);
        await queryRunner.query(`ALTER TABLE "users_events_moderated_events" DROP CONSTRAINT "FK_90375e090112b4910bbe9b3f98e"`);
        await queryRunner.query(`ALTER TABLE "users_events_invited_events" DROP CONSTRAINT "FK_5833bf6d88075d08b2e5b162704"`);
        await queryRunner.query(`ALTER TABLE "users_events_invited_events" DROP CONSTRAINT "FK_c48949e1dcc02341ea8c61eec29"`);
        await queryRunner.query(`ALTER TABLE "users_events_attended_on_behalf_events" DROP CONSTRAINT "FK_f428e8eb01f072bd78ce977cd9b"`);
        await queryRunner.query(`ALTER TABLE "users_events_attended_on_behalf_events" DROP CONSTRAINT "FK_5f5b1cac95cd2a556c9a416f5bb"`);
        await queryRunner.query(`ALTER TABLE "users_events_attended_events" DROP CONSTRAINT "FK_3f31992a49c73b5889663dbb266"`);
        await queryRunner.query(`ALTER TABLE "users_events_attended_events" DROP CONSTRAINT "FK_5c0fa4b1a599d09c968eadf55bb"`);
        await queryRunner.query(`ALTER TABLE "users_events_subscribed_events" DROP CONSTRAINT "FK_74c8a019e92aa8f46da55ce5c7d"`);
        await queryRunner.query(`ALTER TABLE "users_events_subscribed_events" DROP CONSTRAINT "FK_5e1a5059bc9c16f55e092bad913"`);
        await queryRunner.query(`ALTER TABLE "users_users_friended_users" DROP CONSTRAINT "FK_d26a4fce0d47c58f27b0f434e42"`);
        await queryRunner.query(`ALTER TABLE "users_users_friended_users" DROP CONSTRAINT "FK_f666d2e77717f8c25f7b9b570b5"`);
        await queryRunner.query(`ALTER TABLE "users_users_blocked_users" DROP CONSTRAINT "FK_2a43449a5faadcc6dfe9cbba3c5"`);
        await queryRunner.query(`ALTER TABLE "users_users_blocked_users" DROP CONSTRAINT "FK_a1bf6826f7f14b39329e0ad5215"`);
        await queryRunner.query(`ALTER TABLE "users_interests_category" DROP CONSTRAINT "FK_881f7d3889d88ab53bcaf5eb598"`);
        await queryRunner.query(`ALTER TABLE "users_interests_category" DROP CONSTRAINT "FK_90a15f079b117647e5d267dc024"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_55ad94f5c1b4c97960d6d7dc115"`);
        await queryRunner.query(`ALTER TABLE "events" DROP CONSTRAINT "FK_96ce126fb3f1b5368f8e3c02989"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_ded332d78e4026526df1a7dc630"`);
        await queryRunner.query(`DROP INDEX "IDX_dc98eb9fc9fecc8fba0e537169"`);
        await queryRunner.query(`DROP INDEX "IDX_9caedc75d8c28cbe1da074d65b"`);
        await queryRunner.query(`DROP TABLE "events_attendees_invited_users"`);
        await queryRunner.query(`DROP INDEX "IDX_2665f14d503b3feefefff8e877"`);
        await queryRunner.query(`DROP INDEX "IDX_4b10e1dc612af5c704e6221f23"`);
        await queryRunner.query(`DROP TABLE "events_attendees_on_behalf_users"`);
        await queryRunner.query(`DROP INDEX "IDX_55e9eaa2a8199f6d56e8f851bc"`);
        await queryRunner.query(`DROP INDEX "IDX_cc4d1dac2b0c139aa3c722401b"`);
        await queryRunner.query(`DROP TABLE "events_attendees_users"`);
        await queryRunner.query(`DROP INDEX "IDX_765c0346ad3f288fa562eeb3da"`);
        await queryRunner.query(`DROP INDEX "IDX_1236e491674525fdb404597e28"`);
        await queryRunner.query(`DROP TABLE "events_subscribers_users"`);
        await queryRunner.query(`DROP INDEX "IDX_2cb733c6969ffc6b8c24878755"`);
        await queryRunner.query(`DROP INDEX "IDX_6e4d7b93b5823354a0d67c91ad"`);
        await queryRunner.query(`DROP TABLE "events_moderators_users"`);
        await queryRunner.query(`DROP INDEX "IDX_f2a6d806d59cdae47f2cebd16b"`);
        await queryRunner.query(`DROP INDEX "IDX_db7766576cee46f8f492e5cf91"`);
        await queryRunner.query(`DROP TABLE "events_categories_category"`);
        await queryRunner.query(`DROP INDEX "IDX_796d480a170fea3ea9c34dacdc"`);
        await queryRunner.query(`DROP INDEX "IDX_90375e090112b4910bbe9b3f98"`);
        await queryRunner.query(`DROP TABLE "users_events_moderated_events"`);
        await queryRunner.query(`DROP INDEX "IDX_5833bf6d88075d08b2e5b16270"`);
        await queryRunner.query(`DROP INDEX "IDX_c48949e1dcc02341ea8c61eec2"`);
        await queryRunner.query(`DROP TABLE "users_events_invited_events"`);
        await queryRunner.query(`DROP INDEX "IDX_f428e8eb01f072bd78ce977cd9"`);
        await queryRunner.query(`DROP INDEX "IDX_5f5b1cac95cd2a556c9a416f5b"`);
        await queryRunner.query(`DROP TABLE "users_events_attended_on_behalf_events"`);
        await queryRunner.query(`DROP INDEX "IDX_3f31992a49c73b5889663dbb26"`);
        await queryRunner.query(`DROP INDEX "IDX_5c0fa4b1a599d09c968eadf55b"`);
        await queryRunner.query(`DROP TABLE "users_events_attended_events"`);
        await queryRunner.query(`DROP INDEX "IDX_74c8a019e92aa8f46da55ce5c7"`);
        await queryRunner.query(`DROP INDEX "IDX_5e1a5059bc9c16f55e092bad91"`);
        await queryRunner.query(`DROP TABLE "users_events_subscribed_events"`);
        await queryRunner.query(`DROP INDEX "IDX_d26a4fce0d47c58f27b0f434e4"`);
        await queryRunner.query(`DROP INDEX "IDX_f666d2e77717f8c25f7b9b570b"`);
        await queryRunner.query(`DROP TABLE "users_users_friended_users"`);
        await queryRunner.query(`DROP INDEX "IDX_2a43449a5faadcc6dfe9cbba3c"`);
        await queryRunner.query(`DROP INDEX "IDX_a1bf6826f7f14b39329e0ad521"`);
        await queryRunner.query(`DROP TABLE "users_users_blocked_users"`);
        await queryRunner.query(`DROP INDEX "IDX_881f7d3889d88ab53bcaf5eb59"`);
        await queryRunner.query(`DROP INDEX "IDX_90a15f079b117647e5d267dc02"`);
        await queryRunner.query(`DROP TABLE "users_interests_category"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TABLE "category"`);
    }

}
